// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrganisationContactRequest struct {
	OrganisationId       uint32   `protobuf:"varint,1,opt,name=OrganisationId,proto3" json:"OrganisationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrganisationContactRequest) Reset()         { *m = OrganisationContactRequest{} }
func (m *OrganisationContactRequest) String() string { return proto.CompactTextString(m) }
func (*OrganisationContactRequest) ProtoMessage()    {}
func (*OrganisationContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *OrganisationContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationContactRequest.Unmarshal(m, b)
}
func (m *OrganisationContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationContactRequest.Marshal(b, m, deterministic)
}
func (m *OrganisationContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationContactRequest.Merge(m, src)
}
func (m *OrganisationContactRequest) XXX_Size() int {
	return xxx_messageInfo_OrganisationContactRequest.Size(m)
}
func (m *OrganisationContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationContactRequest proto.InternalMessageInfo

func (m *OrganisationContactRequest) GetOrganisationId() uint32 {
	if m != nil {
		return m.OrganisationId
	}
	return 0
}

type ContactResponse struct {
	Contacts             []*ContactResponse_Contact `protobuf:"bytes,1,rep,name=Contacts,proto3" json:"Contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ContactResponse) Reset()         { *m = ContactResponse{} }
func (m *ContactResponse) String() string { return proto.CompactTextString(m) }
func (*ContactResponse) ProtoMessage()    {}
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}

func (m *ContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactResponse.Unmarshal(m, b)
}
func (m *ContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactResponse.Marshal(b, m, deterministic)
}
func (m *ContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactResponse.Merge(m, src)
}
func (m *ContactResponse) XXX_Size() int {
	return xxx_messageInfo_ContactResponse.Size(m)
}
func (m *ContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactResponse proto.InternalMessageInfo

func (m *ContactResponse) GetContacts() []*ContactResponse_Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type ContactResponse_Contact struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Organisation         uint32   `protobuf:"varint,3,opt,name=Organisation,proto3" json:"Organisation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactResponse_Contact) Reset()         { *m = ContactResponse_Contact{} }
func (m *ContactResponse_Contact) String() string { return proto.CompactTextString(m) }
func (*ContactResponse_Contact) ProtoMessage()    {}
func (*ContactResponse_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1, 0}
}

func (m *ContactResponse_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactResponse_Contact.Unmarshal(m, b)
}
func (m *ContactResponse_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactResponse_Contact.Marshal(b, m, deterministic)
}
func (m *ContactResponse_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactResponse_Contact.Merge(m, src)
}
func (m *ContactResponse_Contact) XXX_Size() int {
	return xxx_messageInfo_ContactResponse_Contact.Size(m)
}
func (m *ContactResponse_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactResponse_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_ContactResponse_Contact proto.InternalMessageInfo

func (m *ContactResponse_Contact) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContactResponse_Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ContactResponse_Contact) GetOrganisation() uint32 {
	if m != nil {
		return m.Organisation
	}
	return 0
}

func init() {
	proto.RegisterType((*OrganisationContactRequest)(nil), "OrganisationContactRequest")
	proto.RegisterType((*ContactResponse)(nil), "ContactResponse")
	proto.RegisterType((*ContactResponse_Contact)(nil), "ContactResponse.Contact")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x49, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe1, 0x92, 0xf2, 0x2f, 0x4a,
	0x4f, 0xcc, 0xcb, 0x2c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x73, 0x86, 0x48, 0x06, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0xa9, 0x71, 0xf1, 0x21, 0xcb, 0x7a, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x06, 0xa1, 0x89, 0x2a, 0xcd, 0x61, 0xe4, 0xe2, 0x87, 0x6b, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x15, 0x32, 0xe1, 0xe2, 0x80, 0x0a, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x49,
	0xe8, 0xa1, 0xa9, 0x81, 0xf3, 0xe1, 0x2a, 0xa5, 0x82, 0xb9, 0xd8, 0xa1, 0x6c, 0x21, 0x3e, 0x2e,
	0x26, 0xb8, 0x85, 0x4c, 0x9e, 0x29, 0x42, 0x22, 0x5c, 0xac, 0xae, 0xb9, 0x89, 0x99, 0x39, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x12, 0x17, 0x0f, 0xb2, 0x63, 0x24, 0x98,
	0xc1, 0xea, 0x51, 0xc4, 0x8c, 0xa2, 0xb8, 0xf8, 0xa0, 0x86, 0x06, 0xa7, 0x16, 0x95, 0x65, 0x26,
	0xa7, 0x0a, 0x79, 0x70, 0x89, 0xbb, 0xa7, 0x96, 0x60, 0xf1, 0x79, 0xb1, 0x90, 0xb4, 0x1e, 0xee,
	0x00, 0x91, 0x12, 0x40, 0xf7, 0x42, 0x12, 0x1b, 0x38, 0x1c, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0x3f, 0x73, 0xe1, 0x58, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactServiceClient interface {
	GetOrganisationContacts(ctx context.Context, in *OrganisationContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
}

type contactServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactServiceClient(cc *grpc.ClientConn) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) GetOrganisationContacts(ctx context.Context, in *OrganisationContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, "/ContactService/GetOrganisationContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
type ContactServiceServer interface {
	GetOrganisationContacts(context.Context, *OrganisationContactRequest) (*ContactResponse, error)
}

// UnimplementedContactServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContactServiceServer struct {
}

func (*UnimplementedContactServiceServer) GetOrganisationContacts(ctx context.Context, req *OrganisationContactRequest) (*ContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganisationContacts not implemented")
}

func RegisterContactServiceServer(s *grpc.Server, srv ContactServiceServer) {
	s.RegisterService(&_ContactService_serviceDesc, srv)
}

func _ContactService_GetOrganisationContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganisationContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetOrganisationContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactService/GetOrganisationContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetOrganisationContacts(ctx, req.(*OrganisationContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrganisationContacts",
			Handler:    _ContactService_GetOrganisationContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact.proto",
}
